Increase test time limit
Attempts to fix the following error on Travis:

```
1) build should list only required files:

  Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```